
- name: start the service
  systemd:
    state: started
    daemon_reload: yes
    name: "{{ service_name }}"
    enabled: yes
  become: yes

- name: wait for service to start
  uri:
    url: "https://localhost:{{ health_check_port | default(server_port) }}{{ health_check_uri | default('/actuator/health') }}"
    return_content: yes
    validate_certs: false
  register: _result
  until: _result.status == 200
  retries: 10
  delay: 3
  #failed_when: "'UP' not in _result.content"

- name: get installed version from version.txt file
  slurp:
    src: "{{ installation_folder }}/version.txt"
  register: installed_version
  
- name: print installed version
  debug:
    msg: " Installed version: {{ ((installed_version['content'] | b64decode).split(':')[1] | trim).split('-')[0] }}"

- name: fail if app_version is not equal to installed version
  fail:
    msg: "app_version: {{ app_version }} does not macthed to installed version {{ ((installed_version['content'] | b64decode).split(':')[1] | trim).split('-')[0] }}"
  when: app_version != ((installed_version['content'] | b64decode).split(':')[1] | trim).split('-')[0]
  